name: run tests on github actions

on: workflow_dispatch
jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: pull project
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  '17'

      - name: start selenoid server
        uses: ajinx/selenoid@v
        id: start-selenoid
        continue-on-error: false

      - name: run test
        run: |
         mvn test